### ISSUE TITLE
[Bug] RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB

### ISSUE THREAD

**Issue by zdyshine** [open-mmlab/mmagic#1438]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

sys.platform: linux
Python: 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.5.3
MMCV: 1.7.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMEditing: 0.16.0+unknown

### Reproduces the problem - code sample

./tools/dist_train.sh configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py 2

### Reproduces the problem - command or script

./tools/dist_train.sh configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py 2

### Reproduces the problem - error message

2022-11-15 09:17:23,329 - mmedit - INFO - Exp name: realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds
2022-11-15 09:17:23,334 - mmedit - INFO - Iter [217000/300000]  lr_generator: 1.000e-04, eta: 1 day, 9:10:14, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.8298, loss_clean: 0.1455
2022-11-15 09:19:40,529 - mmedit - INFO - Iter [217100/300000]  lr_generator: 1.000e-04, eta: 1 day, 9:06:32, time: 1.372, data_time: 0.004, memory: 13776, loss_pix: 0.7327, loss_clean: 0.1464
2022-11-15 09:21:57,597 - mmedit - INFO - Iter [217200/300000]  lr_generator: 1.000e-04, eta: 1 day, 9:02:52, time: 1.371, data_time: 0.004, memory: 13776, loss_pix: 0.6168, loss_clean: 0.1427
2022-11-15 09:24:14,631 - mmedit - INFO - Iter [217300/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:59:12, time: 1.370, data_time: 0.004, memory: 13776, loss_pix: 0.3916, loss_clean: 0.1398
2022-11-15 09:26:31,505 - mmedit - INFO - Iter [217400/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:55:34, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.3338, loss_clean: 0.1423
2022-11-15 09:28:48,571 - mmedit - INFO - Iter [217500/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:52:00, time: 1.371, data_time: 0.004, memory: 13776, loss_pix: 0.1727, loss_clean: 0.1422
2022-11-15 09:31:05,626 - mmedit - INFO - Iter [217600/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:48:27, time: 1.370, data_time: 0.005, memory: 13776, loss_pix: 0.1174, loss_clean: 0.1566
2022-11-15 09:33:22,552 - mmedit - INFO - Iter [217700/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:44:55, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.0964, loss_clean: 0.1462
2022-11-15 09:35:39,495 - mmedit - INFO - Iter [217800/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:41:26, time: 1.369, data_time: 0.004, memory: 13776, loss_pix: 0.0861, loss_clean: 0.1430
2022-11-15 09:37:56,536 - mmedit - INFO - Iter [217900/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:37:59, time: 1.370, data_time: 0.005, memory: 13776, loss_pix: 0.0754, loss_clean: 0.1415
2022-11-15 09:40:13,607 - mmedit - INFO - Saving checkpoint at 218000 iterations
2022-11-15 09:40:14,506 - mmedit - INFO - Exp name: realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds
2022-11-15 09:40:14,506 - mmedit - INFO - Iter [218000/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:34:43, time: 1.380, data_time: 0.006, memory: 13776, loss_pix: 0.0770, loss_clean: 0.1414
2022-11-15 09:42:31,459 - mmedit - INFO - Iter [218100/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:31:19, time: 1.370, data_time: 0.005, memory: 13776, loss_pix: 0.0850, loss_clean: 0.1411
2022-11-15 09:44:48,561 - mmedit - INFO - Iter [218200/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:27:57, time: 1.371, data_time: 0.005, memory: 13776, loss_pix: 0.0991, loss_clean: 0.1463
2022-11-15 09:47:05,473 - mmedit - INFO - Iter [218300/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:24:36, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.0903, loss_clean: 0.1416
2022-11-15 09:49:22,390 - mmedit - INFO - Iter [218400/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:21:16, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.0802, loss_clean: 0.1490
2022-11-15 09:51:39,351 - mmedit - INFO - Iter [218500/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:17:57, time: 1.370, data_time: 0.004, memory: 13776, loss_pix: 0.1405, loss_clean: 0.1322
2022-11-15 09:53:56,575 - mmedit - INFO - Iter [218600/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:14:43, time: 1.372, data_time: 0.005, memory: 13776, loss_pix: 0.0747, loss_clean: 0.1213
2022-11-15 09:56:13,549 - mmedit - INFO - Iter [218700/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:11:28, time: 1.370, data_time: 0.004, memory: 13776, loss_pix: 0.0805, loss_clean: 0.1264
2022-11-15 09:58:30,808 - mmedit - INFO - Iter [218800/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:08:17, time: 1.373, data_time: 0.005, memory: 13776, loss_pix: 0.0700, loss_clean: 0.1218
2022-11-15 10:00:47,669 - mmedit - INFO - Iter [218900/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:05:03, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.0702, loss_clean: 0.1177
2022-11-15 10:03:04,989 - mmedit - INFO - Exp name: realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds
2022-11-15 10:03:05,146 - mmedit - INFO - Iter [219000/300000]  lr_generator: 1.000e-04, eta: 1 day, 8:01:55, time: 1.373, data_time: 0.005, memory: 13776, loss_pix: 0.0590, loss_clean: 0.1022
2022-11-15 10:05:22,353 - mmedit - INFO - Iter [219100/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:58:48, time: 1.374, data_time: 0.006, memory: 13776, loss_pix: 0.0607, loss_clean: 0.0837
2022-11-15 10:07:39,353 - mmedit - INFO - Iter [219200/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:55:39, time: 1.370, data_time: 0.005, memory: 13776, loss_pix: 0.0589, loss_clean: 0.0612
2022-11-15 10:09:56,119 - mmedit - INFO - Iter [219300/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:52:29, time: 1.368, data_time: 0.004, memory: 13776, loss_pix: 0.0690, loss_clean: 0.0788
2022-11-15 10:12:13,367 - mmedit - INFO - Iter [219400/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:49:24, time: 1.372, data_time: 0.005, memory: 13776, loss_pix: 0.0587, loss_clean: 0.0703
2022-11-15 10:14:30,596 - mmedit - INFO - Iter [219500/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:46:20, time: 1.372, data_time: 0.005, memory: 13776, loss_pix: 0.0485, loss_clean: 0.0559
2022-11-15 10:16:47,928 - mmedit - INFO - Iter [219600/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:43:19, time: 1.374, data_time: 0.008, memory: 13776, loss_pix: 0.0487, loss_clean: 0.0520
2022-11-15 10:19:04,803 - mmedit - INFO - Iter [219700/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:40:14, time: 1.369, data_time: 0.005, memory: 13776, loss_pix: 0.0430, loss_clean: 0.0454
2022-11-15 10:21:21,725 - mmedit - INFO - Iter [219800/300000]  lr_generator: 1.000e-04, eta: 1 day, 7:37:10, time: 1.369, data_time: 0.004, memory: 13776, loss_pix: 0.0447, loss_clean: 0.0461
Traceback (most recent call last):
  File "./tools/train.py", line 177, in <module>
    main()
  File "./tools/train.py", line 166, in main
    train_model(
  File "/mmediting/mmedit/apis/train.py", line 97, in train_model
    _dist_train(
  File "/mmediting/mmedit/apis/train.py", line 242, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/mmediting/mmedit/core/distributed_wrapper.py", line 126, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mmediting/mmedit/models/restorers/real_basicvsr.py", line 121, in train_step
    fake_g_output, fake_g_lq = self.generator(lq, return_lqs=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmediting/mmedit/models/backbones/sr_backbones/real_basicvsr_net.py", line 87, in forward
    outputs = self.basicvsr(lqs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmediting/mmedit/models/backbones/sr_backbones/basicvsr_net.py", line 154, in forward
    feat_prop = self.forward_resblocks(feat_prop)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmediting/mmedit/models/backbones/sr_backbones/basicvsr_net.py", line 222, in forward
    return self.main(feat)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmediting/mmedit/models/common/sr_backbone_utils.py", line 96, in forward
    return identity + out * self.res_scale
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 1; 23.70 GiB total capacity; 21.43 GiB already allocated; 16.81 MiB free; 22.00 GiB reserved in total by PyTorch)
Killing subprocess 204541
Killing subprocess 204542
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py', '--seed', '0', '--launcher', 'pytorch']' returned non-zero exit status 1.

### Additional information

I tried to reduce the patch size and nfrmaes sent to the network, but OOM still appears after the code runs for a period of time.

**Comment by zengyh1900** [comment]
Hi @zdyshine it seems that OOM happens during normal training. Let me help you to find out the reason. 
Did you share your GPU with others? Did you see the memory increasing during training by running `watch -n 1 nvidia-smi`?
I'm not sure whether it is caused due to shared GPU or the code implementation.

**Comment by zdyshine** [comment]
> Hi @zdyshine it seems that OOM happens during normal training. Let me help you to find out the reason. Did you share your GPU with others? Did you see the memory increasing during training by running `watch -n 1 nvidia-smi`? I'm not sure whether it is caused due to shared GPU or the code implementation.

Thank you for your reply. The machine is for my own use. There are no other programs that occupy video memory. I confirmed that OOM happened suddenly during normal training.

**Comment by zengyh1900** [comment]
> > Hi @zdyshine it seems that OOM happens during normal training. Let me help you to find out the reason. Did you share your GPU with others? Did you see the memory increasing during training by running `watch -n 1 nvidia-smi`? I'm not sure whether it is caused due to shared GPU or the code implementation.
> 
> Thank you for your reply. The machine is for my own use. There are no other programs that occupy video memory. I confirmed that OOM happened suddenly during normal training.

Thanks for reporting this issue! We're checking it and we will update it once we have conclusion! Thanks!

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.
