### ISSUE TITLE
av.error.ExternalError: [Errno 542398533] Generic error in an external library

### ISSUE THREAD

**Issue by truongnhat-ryo** [open-mmlab/mmagic#1685]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

I followed instruction in  README to install packages in virtual env
I only change directory of dataset in config file. The rest was keep original
--------------------------------------------
sys.platform: linux
Python: 3.8.16 (default, Dec  7 2022, 01:12:13) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: Tesla T4
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0+cu111
OpenCV: 4.7.0
MMCV: 1.5.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMEditing: 0.16.1+d18fc44

### Reproduces the problem - code sample

a

### Reproduces the problem - command or script

./tools/dist_train.sh configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py 4

### Reproduces the problem - error message

After 12000 iteration I get this error:

2023-03-04 00:41:12,994 - mmedit - INFO - Exp name: realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds
INFO:mmedit:Exp name: realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds
2023-03-04 00:41:12,994 - mmedit - INFO - Iter(val) [12000]	
INFO:mmedit:Iter(val) [12000]	
2023-03-04 00:45:46,766 - mmedit - INFO - Iter [12100/300000]	lr_generator: 1.000e-04, eta: 8 days, 7:31:21, time: 2.991, data_time: 0.255, memory: 11160, loss_pix: 0.0260, loss_clean: 0.0225
INFO:mmedit:Iter [12100/300000]	lr_generator: 1.000e-04, eta: 8 days, 7:31:21, time: 2.991, data_time: 0.255, memory: 11160, loss_pix: 0.0260, loss_clean: 0.0225
Traceback (most recent call last):
  File "./tools/train.py", line 171, in <module>
    main()
  File "./tools/train.py", line 160, in main
    train_model(
  File "/home/truong/datadrive2/project/mmediting/mmedit/apis/train.py", line 97, in train_model
    _dist_train(
  File "/home/truong/datadrive2/project/mmediting/mmedit/apis/train.py", line 238, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/_utils.py", line 433, in reraise
    raise RuntimeError(msg) from None
RuntimeError: Caught ExternalError in DataLoader worker process 9.
Original Traceback (most recent call last):
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1176, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/truong/datadrive2/project/venv_mmedit/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/truong/datadrive2/project/mmediting/mmedit/datasets/dataset_wrappers.py", line 31, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/truong/datadrive2/project/mmediting/mmedit/datasets/base_sr_dataset.py", line 55, in __getitem__
    return self.pipeline(results)
  File "/home/truong/datadrive2/project/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/truong/datadrive2/project/mmediting/mmedit/datasets/pipelines/random_degradations.py", line 547, in __call__
    results = degradation(results)
  File "/home/truong/datadrive2/project/mmediting/mmedit/datasets/pipelines/random_degradations.py", line 465, in __call__
    results[key] = self._apply_random_compression(results[key])
  File "/home/truong/datadrive2/project/mmediting/mmedit/datasets/pipelines/random_degradations.py", line 444, in _apply_random_compression
    for packet in stream.encode(frame):
  File "av/stream.pyx", line 153, in av.stream.Stream.encode
  File "av/codec/context.pyx", line 482, in av.codec.context.CodecContext.encode
  File "av/codec/context.pyx", line 291, in av.codec.context.CodecContext.open
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ExternalError: [Errno 542398533] Generic error in an external library

### Additional information

Do you know what is root cause of this problem? Thanks

**Comment by Z-Fran** [comment]
Try using the latest version.

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.

**Comment by shinyJY** [comment]
@Z-Fran I also encouter the similar problem when training realbasicvsr. I skip it temporarily by not using the video compression augmentation. 
I want to know whether the latest version means the mmagic codeabse？Besides, is the video compression augmentation important for realbasicvsr training ?
