### ISSUE TITLE
[Bug] the tool(pytorch2onnx) will break when convert basicvsr_reds4 model

### ISSUE THREAD

**Issue by xihao-1223** [open-mmlab/mmagic#1700]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

Traceback (most recent call last):
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/tools/pytorch2onnx.py", line 232, in <module>
    data = test_pipeline(data)
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/mmedit/datasets/pipelines/augmentation.py", line 1093, in __call__
    clip_name = results['key']
KeyError: 'key'

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/tools/pytorch2onnx.py", line 232, in <module>
    data = test_pipeline(data)
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/mmedit/datasets/pipelines/augmentation.py", line 1093, in __call__
    clip_name = results['key']
KeyError: 'key'

### Reproduces the problem - command or script

parser.add_argument('--config', type=str, default="/workspace/***/test_env/pymodels/mmediting/mmediting/configs/restorers/basicvsr/basicvsr_reds4.py", help='test config file path')
parser.add_argument('--checkpoint', type=str, default="/workspace/***/test_env/pymodels/mmediting/mmediting/weights/basicvsr_reds4_20120409-0e599677.pth", help='checkpoint file')
    

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/tools/pytorch2onnx.py", line 232, in <module>
    data = test_pipeline(data)
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/workspace/xhao/test_env/pymodels/mmediting/mmediting/mmedit/datasets/pipelines/augmentation.py", line 1093, in __call__
    clip_name = results['key']
KeyError: 'key'

### Additional information

if i want convert a basicvsr_reds4 model to onnx, i need to do ? i do some follow the get_start.md but get an error

**Comment by Z-Fran** [comment]
We will deprecate it. Please use https://github.com/open-mmlab/mmdeploy .

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.
