### ISSUE TITLE
[Bug] 视频插针运行失败

### ISSUE THREAD

**Issue by changqing91** [open-mmlab/mmagic#1736]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

mmediting % python mmedit/utils/collect_env.py
/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/changqing/Github/mmediting/mmedit/utils/collect_env.py", line 17, in <module>
    for name, val in collect_env().items():
  File "/Users/changqing/Github/mmediting/mmedit/utils/collect_env.py", line 10, in collect_env
    env_info = collect_base_env()
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/utils/env.py", line 124, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/ops/ball_query.py", line 9, in <module>
    ext_module = ext_loader.load_ext(
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: stack_ball_query_forward miss in module _ext

### Reproduces the problem - code sample

mmediting % python demo/video_interpolation_demo.py \
    configs/video_interpolators/cain/cain_b5_320k_vimeo-triplet.py \
    https://download.openmmlab.com/mmediting/video_interpolators/cain/cain_b5_320k_vimeo-triple_20220117-647f3de2.pth \
    tests/data/test_inference.mp4 \
    tests/data/test_inference_vfi_out.mp4 \
    --fps-multiplier 2.0

### Reproduces the problem - command or script

mmediting % python demo/video_interpolation_demo.py \
    configs/video_interpolators/cain/cain_b5_320k_vimeo-triplet.py \
    https://download.openmmlab.com/mmediting/video_interpolators/cain/cain_b5_320k_vimeo-triple_20220117-647f3de2.pth \
    tests/data/test_inference.mp4 \
    tests/data/test_inference_vfi_out.mp4 \
    --fps-multiplier 2.0

### Reproduces the problem - error message

/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/changqing/Github/mmediting/demo/video_interpolation_demo.py", line 6, in <module>
    from mmedit.apis import init_model, video_interpolation_inference
  File "/Users/changqing/Github/mmediting/mmedit/apis/__init__.py", line 4, in <module>
    from .matting_inference import init_model, matting_inference
  File "/Users/changqing/Github/mmediting/mmedit/apis/matting_inference.py", line 8, in <module>
    from mmedit.models import build_model
  File "/Users/changqing/Github/mmediting/mmedit/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401, F403
  File "/Users/changqing/Github/mmediting/mmedit/models/backbones/__init__.py", line 14, in <module>
    from .sr_backbones import (EDSR, LIIFEDSR, LIIFRDN, RDN, SRCNN, BasicVSRNet,
  File "/Users/changqing/Github/mmediting/mmedit/models/backbones/sr_backbones/__init__.py", line 3, in <module>
    from .basicvsr_pp import BasicVSRPlusPlus
  File "/Users/changqing/Github/mmediting/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 6, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/ops/ball_query.py", line 9, in <module>
    ext_module = ext_loader.load_ext(
  File "/Users/changqing/anaconda3/lib/python3.10/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: stack_ball_query_forward miss in module _ext

**Comment by Z-Fran** [comment]
Please use latest mmagic， and run:
```
python demo/mmagic_inference_demo.py \
        --model-name cain \
        --video input_path \
        --result-out-dir output_path
```

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.
