### ISSUE TITLE
AssertionError: mmcv==1.7.1 is used but incompatible. Please install mmcv-full>=(2, 0, 0, 0, -1, 1), <(2, 1, 0, 0, 0, 0).

### ISSUE THREAD

**Issue by ArrXiao** [open-mmlab/mmagic#1756]
I run python tools/test.py configs/real_basicvsr/realbasicvsr_c64b20-1x30x8_8xb1-lr5e-5-150k_reds.py https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds_20211104-52f77c2c.pth

AssertionError: mmcv==1.7.1 is used but incompatible. Please install mmcv-full>=(2, 0, 0, 0, -1, 1), <(2, 1, 0, 0, 0, 0).

![image](https://user-images.githubusercontent.com/90619366/232246258-b46ad285-75cb-40d5-92e7-fd30fd42aeea.png)
but mmcv-full has changed,not have 2.0.0,I dont know how to fix.
![image](https://user-images.githubusercontent.com/90619366/232246683-001674a0-4286-4ad8-bae0-a025bfd7141d.png)

**Comment by ArrXiao** [comment]
sorry this is the right picture
![image](https://user-images.githubusercontent.com/90619366/232246652-c82c6e66-f022-4a64-91a8-08056fc1ad22.png)

**Comment by Z-Fran** [comment]
Please run ‘pip install mmcv==2.0.0’

**Comment by ArrXiao** [comment]
> Please run ‘pip install mmcv==2.0.0’

In the picture above, I have installed mmcv2.0.0, but there is a problem with recognition

**Comment by Z-Fran** [comment]
Please run ‘pip uninstall mmcv-full’

**Comment by kaigeli** [comment]
when i install mmcv-full, the max mmcv version is 1.7.1. test error:
 python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
/home/kaigeli/.local/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/kaigeli/program/mmtracking/mmtrack/__init__.py", line 5, in <module>
    import mmdet
  File "/home/kaigeli/.local/lib/python3.8/site-packages/mmdet/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

then, I uninstall mmcv-full, and install mmcv=2.0.0, I got this error:
python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/kaigeli/program/mmtracking/mmtrack/__init__.py", line 62, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <2.0.0.

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.

**Comment by TheWayToGlary** [comment]
It renamed the package name mmcv to mmcv-lite and mmcv-full to mmcv in PR https://github.com/open-mmlab/mmcv/pull/2235. Also, change the default value of the environment variable MMCV_WITH_OPS from 0 to 1.

**Comment by TheWayToGlary** [comment]
It could be a code refactoring issue. Because the company refactored the code, the version we downloaded shows mmcv, but is actually equivalent to the previous MMCV-Full
