### ISSUE TITLE
raise ValueError "ref_path" in restoration_demo.py

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmagic#1761]
my environment as follow:
- mmcv        2.0.0rc1     
- mmedit        1.0.0rc7     
- mmengine      0.7.2
the code branch is dev-1.x.

my command:
```
python /opt/mmediting/demo/restoration_demo.py /opt/mmediting/configs/ttsr/ttsr-gan_x4c64b16_1xb9-500k_CUFED.py https://download.openmmlab.com/mmediting/restorers/ttsr/ttsr-gan_x4_c64b16_g1_500k_CUFED_20210626-2ab28ca0.pth /opt/mmediting/tests/data/frames/sequence/gt/sequence_1/00000000.png /opt/mmediting/demo/demo_out.png --ref-path /opt/mmedting/tests/data/frames/sequence/gt/sequence_1/00000001.png
```
and the traceback :
```
Traceback (most recent call last):
  File "/opt/mmediting/demo/restoration_demo.py", line 61, in <module>
    main()
  File "/opt/mmediting/demo/restoration_demo.py", line 37, in main
    raise ValueError('It seems that you did not input a valid '
ValueError: It seems that you did not input a valid "ref_path". Please double check your input, or you may want to use "ref_path=None" for single restoration.
```

**Comment by Z-Fran** [comment]
Please use the latest mmagic, and run:
```
python mmagic_inference_demo.py \
        --model-name ttsr \
        --img tests/data/frames/sequence/gt/sequence_1/00000000.png \
        --ref tests/data/frames/sequence/gt/sequence_1/00000001.png \
        --result-out-dir ouput.png
```

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.
