### ISSUE TITLE
generation_demo.py KeyError: 'alpha_path'

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmagic#1779]
my environment :
- mmcv-ful 1.7.1
- mmedit 0.16.1
my mmediting code baranch is master .

command
```
python /opt/mmediting/demo/generation_demo.py /opt/mmediting/configs/mattors/dim/dim_stage3_v16_pln_1x1_1000k_comp1k.py dim_stage3_v16_pln_1x1_1000k_comp1k_SAD-50.6_20200609_111851-647f24b6.pth data/00000002.png demo/demo_out.png
```

Traceback:
```
Traceback (most recent call last):
  File "/opt/mmediting/demo/generation_demo.py", line 45, in <module>
    main()
  File "/opt/mmediting/demo/generation_demo.py", line 37, in main
    output = generation_inference(model, args.img_path, args.unpaired_path)
  File "/opt/mmediting/mmedit/apis/generation_inference.py", line 31, in generation_inference
    data = test_pipeline(data)
  File "/opt/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/opt/mmediting/mmedit/datasets/pipelines/loading.py", line 66, in __call__
    filepath = str(results[f'{self.key}_path'])
KeyError: 'alpha_path'
```

**Comment by Z-Fran** [comment]
Please follow this https://github.com/open-mmlab/mmagic/pull/1833

**Comment by Z-Fran** [comment]
Closing this issue since the bug has been fixed in a merged pull request. Please feel free to reopen it if it has not been fixed.
