### ISSUE TITLE
some questions in video_interpolation_demo.py 

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmagic#1783]
my environment :
- mmcv-ful 1.7.1
- mmedit 0.16.1
my mmediting code baranch is master .

command
```
pytest command: python /opt/mmediting/demo/video_interpolation_demo.py /opt/mmediting/configs/video_interpolators/cain/cain_b5_g1b32_vimeo90k_triplet.py cain_b5_g1b32_vimeo90k_triplet_20220530-3520b00c.pth /opt/mmediting/tests/data/test_inference.mp4 demo/test_inference_vfi_out.mp4 --fps 60.0
```

Traceback:
```
Traceback (most recent call last):
  File "/opt/mmediting/demo/video_interpolation_demo.py", line 89, in <module>
    main()
  File "/opt/mmediting/demo/video_interpolation_demo.py", line 69, in main
    if args.device < 0 or not torch.cuda.is_available():
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by Z-Fran** [comment]
Please use the latest mmagic， and run:
```
python demo/mmagic_inference_demo.py \
        --model-name cain \
        --video input_path \
        --result-out-dir output_path
```

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.
