### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'controlnet_aux'

### ISSUE THREAD

**Issue by chenchch94** [open-mmlab/mmagic#1820]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

(develop_py38) root@di-20230327111548-gzv6w:/vepfs/chenchucheng/code/mmagic_demo/mmagic-main# python
Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmagic.apis import MMagicInferencer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vepfs/chenchucheng/code/mmagic_demo/mmagic-main/mmagic/apis/__init__.py", line 2, in <module>
    from .mmagic_inferencer import MMagicInferencer
  File "/vepfs/chenchucheng/code/mmagic_demo/mmagic-main/mmagic/apis/mmagic_inferencer.py", line 11, in <module>
    from .inferencers import Inferencers
  File "/vepfs/chenchucheng/code/mmagic_demo/mmagic-main/mmagic/apis/inferencers/__init__.py", line 9, in <module>
    from .controlnet_animation_inferencer import ControlnetAnimationInferencer
  File "/vepfs/chenchucheng/code/mmagic_demo/mmagic-main/mmagic/apis/inferencers/controlnet_animation_inferencer.py", line 11, in <module>
    from controlnet_aux import HEDdetector
ModuleNotFoundError: No module named 'controlnet_aux'

### Reproduces the problem - code sample

ModuleNotFoundError: No module named 'controlnet_aux'

### Reproduces the problem - command or script

ModuleNotFoundError: No module named 'controlnet_aux'

### Reproduces the problem - error message

ModuleNotFoundError: No module named 'controlnet_aux'

### Additional information

ModuleNotFoundError: No module named 'controlnet_aux'

**Comment by chenchch94** [comment]
pip install controlnet_aux
