### ISSUE TITLE
inpainting功能：如何进行批量图片的测试，并且每张图片有其对应的mask。

### ISSUE THREAD

**Issue by bearatom** [open-mmlab/mmagic#1859]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

环境安装没有问题

### Reproduces the problem - code sample

无

### Reproduces the problem - command or script

我想实现标题所示的功能，输入了如下命令：
python tools/test.py configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_test.py checkpoint/latest.pth --save-path work_dirs/results
我在deepfillv2_256x256_8x2_test.py文件中修改了代码，以下是修改后的结果：
test_pipeline = [
    dict(type='LoadImageFromFile', key='gt_img'),
    dict(
         type='LoadMask',
         mask_mode='file',
         mask_config=dict(
             mask_list_file='data/1_mask.txt',
             prefix='data/1_mask/',
             mask_path='data/1_mask/',
             io_backend='local',
             color_type='unchanged',
             file_client_kwargs=dict())),
....
主要是将mask_mode改为'file',但在输入命令后提示报错见error message
我应该如何解决这个问题呢

### Reproduces the problem - error message

Traceback (most recent call last):
  File "C:\Users\LiKang\mmediting\tools\test.py", line 156, in <module>
    main()
  File "C:\Users\LiKang\mmediting\tools\test.py", line 115, in main
    outputs = single_gpu_test(
  File "c:\users\likang\mmediting\mmedit\apis\test.py", line 41, in single_gpu_test
    for data in data_loader:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\users\likang\mmediting\mmedit\datasets\base_dataset.py", line 76, in __getitem__
    return self.prepare_test_data(idx)
  File "c:\users\likang\mmediting\mmedit\datasets\base_dataset.py", line 59, in prepare_test_data
    return self.pipeline(results)
  File "c:\users\likang\mmediting\mmedit\datasets\pipelines\compose.py", line 42, in __call__
    data = t(data)
  File "c:\users\likang\mmediting\mmedit\datasets\pipelines\loading.py", line 416, in __call__
    mask = self._get_mask_from_file(results['mask_path'])
KeyError: 'mask_path'

### Additional information

十分感谢

**Comment by Z-Fran** [comment]
请参考 https://github.com/open-mmlab/mmagic/blob/main/configs/aot_gan/aot-gan_smpgan_4xb4_places-512x512.py#L70

**Comment by bearatom** [comment]
@Z-Fran 你好，非常感谢你回答我的问题。在你提到的文件中他使用的mask_mode是set，根据注释含义为在mask中随机选择一张，在运行过程中也不会有有关mask_path的报错。我需要运行的是mask_mode是file，即每张图片对应自己的一张mask，运行过程会出现上述报错，请问该怎么解决呢，感谢！

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.

**Comment by maoqiuerer** [comment]
我使用test的命令 python tools/test.py configs/deepfillv2/deepfillv2_8xb2_places-256x256.py deepfillv2_256x256_8x2_places_20200619-10d15793.pth 测试，但是我想使用自己文件夹下的mask，我该修改哪些地方呢
