### ISSUE TITLE
[Bug] av.error: [Errno 542398533] Generic error in an external library

### ISSUE THREAD

**Issue by YikaiHua** [open-mmlab/mmagic#1864]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

Python 3.8.5
CUDA available: True
Pytorch: 1.8.0+cu112
GPU: V100
MMCV: 2.0.0
MMagic: 1.0.0

The docker env is based on a pytorch container provided by nvidia.  
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-02.html#rel_21.02

### Reproduces the problem - code sample

configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py

data_root = 'data'

train_dataloader = dict(
    num_workers=10,
    batch_size=2,
    persistent_workers=False,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type='BasicFramesDataset',
        metainfo=dict(dataset_type='reds', task_name='vsr'),
        data_root=f'{data_root}/REDS',
        data_prefix=dict(img='train_sharp_sub', gt='train_sharp_sub'),
        depth=1,
        num_input_frames=15,
        pipeline=train_pipeline))

val_dataloader = dict(
    num_workers=1,
    batch_size=1,
    persistent_workers=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='BasicFramesDataset',
        metainfo=dict(dataset_type='udm10', task_name='vsr'),
        data_root=f'{data_root}/UDM10',
        data_prefix=dict(img='BIx4', gt='GT'),
        pipeline=val_pipeline))
......

### Reproduces the problem - command or script

bash tools/dist_train.sh configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py 8

### Reproduces the problem - error message

05/16 06:20:28 - mmengine - INFO - Iter(train) [  8500/300000]  generator.lr: 1.0000e-04  eta: 4 days, 13:06:02  time: 1.3740  data_time: 0.1264  memory: 10821  loss_pix: 0.0551  loss_clean: 0.0369
05/16 06:22:40 - mmengine - INFO - Iter(train) [  8600/300000]  generator.lr: 1.0000e-04  eta: 4 days, 13:02:33  time: 1.3255  data_time: 0.0701  memory: 10821  loss_pix: 0.0567  loss_clean: 0.0389
Traceback (most recent call last):
File "tools/train.py", line 114, in <module>
main()
File "tools/train.py", line 107, in main
runner.train()
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1721, in train
model = self.train_loop.run()  # type: ignore
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 277, in run
data_batch = next(self.dataloader_iterator)
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 164, in __next__
data = next(self._iterator)
File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
data = self._next_data()
File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
return self._process_data(data)
File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
data.reraise()
File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
raise self.exc_type(msg)
File "av/error.pyx", line 78, in av.error.FFmpegError.__init__
TypeError: __init__() takes at least 3 positional arguments (2 given)

When I print the concrete exception further, the error is: [Errno 542398533] Generic error in an external library.

### Additional information

I have noticed that there is a similar issue with the same problem: https://github.com/open-mmlab/mmagic/issues/1685. The advice is to use the latest version. My codebase has already in lateset version (hash c6712a76), and the version of av is 10.0.0 (also the lateset verison), but the problem still exists.
I want to know how to solve this problem and why it happens during the training?

**Comment by Z-Fran** [comment]
This may be a ffmpeg's error.

**Comment by Z-Fran** [comment]
By the way, MMCV: 2.0.0 needs PyTorch > 1.8.1

**Comment by Z-Fran** [comment]
Closing due to inactivity, please reopen if there are any further problems.
