### ISSUE TITLE
[Feature] how to use gradio_inpainting.py?

### ISSUE THREAD

**Issue by xddun** [open-mmlab/mmagic#1958]
### What's the feature?

 I fail to use `python demo/gradio_inpainting.py` , I couldn't find a tutorial on how to use this. thx~
 
 $ python demo/gradio_inpainting.py
==model_name aot_gan
==meta_file_dir /ssd/xiedong/workplace/mmagic
Editable project location: /ssd/xiedong/workplace/mmagic
Requires: av, click, controlnet_aux, diffusers, einops, face-alignment, facexlib, lmdb, lpips, mediapipe, numpy, opencv-python, pandas, Pillow, resize_right, tensorboard, transformers
Required-by:
//configs/aot_gan/metafile.yml
Traceback (most recent call last):
  File "demo/gradio_inpainting.py", line 324, in <module>
    inpaintingGradio = InpaintingGradio()
  File "demo/gradio_inpainting.py", line 47, in __init__
    InpaintingGradio.init_inference_supported_models_cfg()
  File "demo/gradio_inpainting.py", line 160, in init_inference_supported_models_cfg
    with open(meta_file_dir, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/ssd/xiedong/workplace/mmagic\nEditable project location: /ssd/xiedong/workplace/mmagic\nRequires: av, click, controlnet_aux, diffusers, einops, face-alignment, facexlib, lmdb, lpips, mediapipe, numpy, opencv-python, pandas, Pillow, resize_right, tensorboard, transformers\nRequired-by: \n//configs/aot_gan/metafile.yml'

**Comment by xddun** [comment]
Does anyone know how to execute this interactive program ?

**Comment by Fearblade66** [comment]
Id like to know as well...
