### ISSUE TITLE
[Bug] raise ValueError(f'Unknown inferencer task: {self.task}') ValueError: Unknown inferencer task: Text2Image, Inpainting

### ISSUE THREAD

**Issue by hs756149694** [open-mmlab/mmagic#1992]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

pytorch 1.1.0 cuda 11.3 pip install

### Reproduces the problem - code sample

from mmagic.apis import MMagicInferencer
sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
text_prompts = 'A panda is having dinner at KFC'
result_out_dir = 'output/sd_res.png'
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)

### Reproduces the problem - command or script

from mmagic.apis import MMagicInferencer
sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
text_prompts = 'A panda is having dinner at KFC'
result_out_dir = 'output/sd_res.png'
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)

### Reproduces the problem - error message

Traceback (most recent call last):
  File "D:\mmaigc\mmagic-main\demoTest.py", line 2, in <module>
    sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
  File "D:\mmaigc\mmagic-main\mmagic\apis\mmagic_inferencer.py", line 140, in __init__
    self.inferencer = Inferencers(
  File "D:\mmaigc\mmagic-main\mmagic\apis\inferencers\__init__.py", line 95, in __init__
    raise ValueError(f'Unknown inferencer task: {self.task}')
ValueError: Unknown inferencer task: Text2Image, Inpainting

### Additional information

Error reported using instance code

**Comment by hs756149694** [comment]
![image](https://github.com/open-mmlab/mmagic/assets/52195458/5aacbbfa-a27f-4ee8-8b2c-d6e1207f6464)

**Comment by hs756149694** [comment]
how to solve it！

**Comment by LeoXing1996** [comment]
@hs756149694 , we have already fixed this in #1995 , you can pull the latest main branch to solve this.
