### ISSUE TITLE
I followed the official installation tutorial and tried 3 times to keep this error

### ISSUE THREAD

**Issue by tl31707chy** [open-mmlab/mmagic#2025]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

win11：

conda create --name mmagic python=3.8 -y
conda activate mmagic
conda install pytorch=1.10 torchvision cpuonly -c pytorch
pip install -U openmim
mim install 'mmcv>=2.0.0'
mim install 'mmengine'
mim install 'mmagic'
python -c "import mmagic; print(mmagic.__version__)"

### Reproduces the problem - code sample

from mmagic.apis import MMagicInferencer
sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
text_prompts = 'A panda is having dinner at KFC'
result_out_dir = 'output/sd_res.png'
sd_inferencer.infer(text=text_prompts, result_out_dir=result_out_dir)

### Reproduces the problem - command or script

Execute directly with pychram

### Reproduces the problem - error message

Traceback (most recent call last):
  File "D:/PycharmProjects/test_demo/main.py", line 2, in <module>
    sd_inferencer = MMagicInferencer(model_name='stable_diffusion')
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\apis\mmagic_inferencer.py", line 140, in __init__
    self.inferencer = Inferencers(
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\apis\inferencers\__init__.py", line 80, in __init__
    self.inferencer = Text2ImageInferencer(
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\apis\inferencers\base_mmagic_inferencer.py", line 57, in __init__
    register_all_modules()
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\utils\setup_env.py", line 25, in register_all_modules
    import mmagic.evaluation  # noqa: F401,F403
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\evaluation\__init__.py", line 2, in <module>
    from .evaluator import Evaluator
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\evaluation\evaluator.py", line 12, in <module>
    from .metrics.base_gen_metric import GenMetric
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\evaluation\metrics\__init__.py", line 12, in <module>
    from .niqe import NIQE, niqe
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\evaluation\metrics\niqe.py", line 12, in <module>
    from mmagic.datasets.transforms import MATLABLikeResize
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\datasets\transforms\__init__.py", line 2, in <module>
    from .albu_function import AlbuCorruptFunction, PairedAlbuTransForms
  File "C:\Users\admin\.conda\envs\mmagic\lib\site-packages\mmagic\datasets\transforms\albu_function.py", line 4, in <module>
    import albumentations as albu
ModuleNotFoundError: No module named 'albumentations'

**Comment by 1027690140** [comment]
how you solve it ?

**Comment by EndrrSB** [comment]
`pip install albumentations`
