### ISSUE TITLE
[Bug]  Can not use `ConcatImageVisualizer`  in train step. / 在Train阶段可视化存在bug

### ISSUE THREAD

**Issue by Pengyang233** [open-mmlab/mmagic#2118]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

English is bad, so I write it in Chinese.

`BasicViaualizationHook` 里的`_after_iter`在`Train`和`Val`和`Test`的`after_iter`阶段被调用，来进行相关可视化操作，通过接受 `outputs` 来进行可视化，这里`outputs`需要是`DataSample` 类型

在 `BaseEditModel` 里，`IterTrainLoop` 和 `EpochBasedLoop` 的 `outputs` 是仅含有 loss 的字典，不是DataSample类型，所以不能在
`BasicViaualizationHook`里的`_after_iter`函数被解析，从而报错。

下面是我的修改，有点low，修改位置是`mmagic/engine/hooks/visualization_hook.py`的`BasicVisualizationHook._after_iter` 函数
```python
        if mode == 'train':  #* 20240126 bug fix. Train 阶段传入的 outputs 是只含有 'loss' 的字典，不是DataSample类型。
            if self.every_n_inner_iters(batch_idx, interval):
                data_sample_0 = data_batch['data_samples'][0]  #* 只存每个 batch 的第一个就行了吧?
                data_sample_0.set_tensor_data({'input': data_batch['inputs'][0]})
                runner.visualizer.add_datasample(data_sample_0, step=runner.iter)
        else:
            if self.every_n_inner_iters(batch_idx, interval):
                for data_sample in outputs:
                    runner.visualizer.add_datasample(data_sample, step=runner.iter)
```

### Reproduces the problem - code sample

vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    _scope_='mmagic',
    type='ConcatImageVisualizer',
    vis_backends=vis_backends,
    pixel_range = {
        'img_vis': [0,1],
        'gt_img': [0,1]
        },
    fn_key='gt_path',
    img_keys=['gt_img', 'img_vis'],
    bgr2rgb=False,
    )
custom_hooks = [dict(_scope_='mmagic',type='BasicVisualizationHook', interval=1, on_train=True, on_val=False)]

### Reproduces the problem - command or script

CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29999 tools/dist_train.sh \
configs/gaussSharpen_noAdjust.py 4

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/mmagic/mmagic/visualization/concat_visualizer.py", line 70, in add_datasample
    **data_sample.to_dict(),
AttributeError: 'str' object has no attribute 'to_dict'

**Comment by ryougishikifor214** [comment]
well done 你做的好呀做的好呀.jpg
小参考(抄）一下

**Comment by ryougishikifor214** [comment]
> ### Prerequisite
> * [x]  I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.[x]  I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.[x]  The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).
> 
> ### Task
> I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.
> 
> ### Branch
> main branch https://github.com/open-mmlab/mmagic
> 
> ### Environment
> English is bad, so I write it in Chinese.
> 
> `BasicViaualizationHook` 里的`_after_iter`在`Train`和`Val`和`Test`的`after_iter`阶段被调用，来进行相关可视化操作，通过接受 `outputs` 来进行可视化，这里`outputs`需要是`DataSample` 类型
> 
> 在 `BaseEditModel` 里，`IterTrainLoop` 和 `EpochBasedLoop` 的 `outputs` 是仅含有 loss 的字典，不是DataSample类型，所以不能在 `BasicViaualizationHook`里的`_after_iter`函数被解析，从而报错。
> 
> 下面是我的修改，有点low，修改位置是`mmagic/engine/hooks/visualization_hook.py`的`BasicVisualizationHook._after_iter` 函数
> 
>         if mode == 'train':  #* 20240126 bug fix. Train 阶段传入的 outputs 是只含有 'loss' 的字典，不是DataSample类型。
>             if self.every_n_inner_iters(batch_idx, interval):
>                 data_sample_0 = data_batch['data_samples'][0]  #* 只存每个 batch 的第一个就行了吧?
>                 data_sample_0.set_tensor_data({'input': data_batch['inputs'][0]})
>                 runner.visualizer.add_datasample(data_sample_0, step=runner.iter)
>         else:
>             if self.every_n_inner_iters(batch_idx, interval):
>                 for data_sample in outputs:
>                     runner.visualizer.add_datasample(data_sample, step=runner.iter)
> ### Reproduces the problem - code sample
> vis_backends = [dict(type='LocalVisBackend')] visualizer = dict( _scope_='mmagic', type='ConcatImageVisualizer', vis_backends=vis_backends, pixel_range = { 'img_vis': [0,1], 'gt_img': [0,1] }, fn_key='gt_path', img_keys=['gt_img', 'img_vis'], bgr2rgb=False, ) custom_hooks = [dict(_scope_='mmagic',type='BasicVisualizationHook', interval=1, on_train=True, on_val=False)]
> 
> ### Reproduces the problem - command or script
> CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29999 tools/dist_train.sh configs/gaussSharpen_noAdjust.py 4
> 
> ### Reproduces the problem - error message
> Traceback (most recent call last): File "/mmagic/mmagic/visualization/concat_visualizer.py", line 70, in add_datasample **data_sample.to_dict(), AttributeError: 'str' object has no attribute 'to_dict'
> 
> ### Additional information
> _No response_

well done 你做的好呀做的好呀.jpg
小参考(抄）一下
